# Go tabanlı backend için Dockerfile
FROM golang:1.21 AS builder

WORKDIR /app

# Modülleri kopyalayıp yükleyelim
COPY go.mod go.sum ./
RUN go mod tidy

# Uygulama dosyalarını kopyalayalım
COPY . .

# Go uygulamasını derleyelim
RUN go build -o main .

# Küçük bir imaj oluşturup çalıştırma aşamasına geçiyoruz
FROM alpine:latest

WORKDIR /root/

# Derlenen binary'yi al
COPY --from=builder /app/main .

# Uygulamayı 8080 portunda çalıştır
EXPOSE 8080
CMD ["./main"]
